apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\The_F\Downloads\kompose-windows-amd64 (1).exe convert -f C:\Users\The_F\source\repos\Miro-Services\src\docker-compose.yml -v
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: catalogdb
  name: catalogdb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: catalogdb
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\The_F\Downloads\kompose-windows-amd64 (1).exe convert -f C:\Users\The_F\source\repos\Miro-Services\src\docker-compose.yml -v
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: catalogdb
    spec:
      containers:
        - name: catalogdb
          image: mongo:6.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: Pass123!
            - name: MONGO_INITDB_DATABASE
              value: CatalogDb
          volumeMounts:
            - name: catalogdb-storage
              mountPath: /data/db
      volumes:
        - name: catalogdb-storage
          emptyDir: {}
      restartPolicy: Always
